# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from mhyt import yt_download


class Ui_Youtube_Downloader(object):
    def setupUi(self, Youtube_Downloader):
        Youtube_Downloader.setObjectName("Youtube_Downloader")
        Youtube_Downloader.resize(645, 405)
        self.centralwidget = QtWidgets.QWidget(Youtube_Downloader)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 20, 451, 41))
        self.label.setMaximumSize(QtCore.QSize(451, 16777215))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 91, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 120, 71, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.link = QtWidgets.QLineEdit(self.centralwidget)
        self.link.setGeometry(QtCore.QRect(130, 80, 501, 25))
        self.link.setObjectName("link")
        self.titulo = QtWidgets.QLineEdit(self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(130, 120, 501, 25))
        self.titulo.setObjectName("titulo")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 160, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.video_unitario = QtWidgets.QRadioButton(self.centralwidget)
        self.video_unitario.setGeometry(QtCore.QRect(200, 200, 112, 23))
        self.video_unitario.setObjectName("video_unitario")
        self.audio = QtWidgets.QRadioButton(self.centralwidget)
        self.audio.setGeometry(QtCore.QRect(200, 240, 112, 23))
        self.audio.setObjectName("audio")
        self.iniciar_download = QtWidgets.QPushButton(self.centralwidget)
        self.iniciar_download.setGeometry(QtCore.QRect(180, 290, 251, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.iniciar_download.setFont(font)
        self.iniciar_download.setObjectName("iniciar_download")
        Youtube_Downloader.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Youtube_Downloader)
        self.statusbar.setObjectName("statusbar")
        Youtube_Downloader.setStatusBar(self.statusbar)

        self.retranslateUi(Youtube_Downloader)
        QtCore.QMetaObject.connectSlotsByName(Youtube_Downloader)

        self.iniciar_download.clicked.connect(self.download)

    def download(self):
        if self.video_unitario.isChecked() == True:
            url = self.link.text()
            titulo = self.titulo.text()
            titulo_mp4 = titulo + '.mp4'
            yt_download(url, titulo_mp4)
   
        elif self.audio.isChecked() == True:
            try:    
                url = self.link.text()
                titulo = self.titulo.text()
                titulo_mp3 = titulo + '.mp3'
                yt_download(url, titulo_mp3, ismusic = True, codec = 'mp3')           
            except:
                pass

    def retranslateUi(self, Youtube_Downloader):
        _translate = QtCore.QCoreApplication.translate
        Youtube_Downloader.setWindowTitle(_translate("Youtube_Downloader", "MainWindow"))
        self.label.setText(_translate("Youtube_Downloader", "YouTube - Downloader"))
        self.label_3.setText(_translate("Youtube_Downloader", "Link:"))
        self.label_4.setText(_translate("Youtube_Downloader", "Título: "))
        self.label_5.setText(_translate("Youtube_Downloader", "Opções:"))
        self.video_unitario.setText(_translate("Youtube_Downloader", "Vídeo;"))
        self.audio.setText(_translate("Youtube_Downloader", "Música."))
        self.iniciar_download.setText(_translate("Youtube_Downloader", "Iniciar Download"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Youtube_Downloader = QtWidgets.QMainWindow()
    ui = Ui_Youtube_Downloader()
    ui.setupUi(Youtube_Downloader)
    Youtube_Downloader.show()
    sys.exit(app.exec_())
